install:
  - sudo apt-get update
  - sudo mkdir -p /var/lib/docker
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d
  - sudo apt-get install -y slirp wget aufs-tools cgroup-lite
  - sudo wget -qO- https://get.docker.com/ | sh
  - curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
  - chmod +x linux

script:
  - ./linux quiet mem=2G rootfstype=hostfs rw eth0=slirp,,/usr/bin/slirp-fullbolt init=$(pwd)/uml.sh WORKDIR=$(pwd) HOME=$HOME; exit `cat $(pwd)/$DIR/exit.status`
