db:
  image: postgres

web:
  build: .
  command: 'bash -c ''bin/rails server --binding 0.0.0.0 --port $PORT'''
  working_dir: /app/user
  links:
    - db
  env_file: .env
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  ports:
    - '8080:8080'

shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
