db:
  image: postgres

web:
  build: .
  command: /app/user/bin/rails server --binding 0.0.0.0
  ports:
    - '3000:3000'
  links:
    - db
  environment:
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  env_file: .env
