web:
  build: .
  command: 'bash -c ''bin/rails server --binding 0.0.0.0 --port $PORT'''
  working_dir: /app/user
  environment:
    PORT: 3000
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '3000'
  links:
    - herokuPostgresql
herokuPostgresql:
  image: postgres
